### PR TITLE
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/SSDP-165/Enable-schema-evolution-in-the-Airbyte-Databricks-connector

### PR DESCRIPTION
**Pull request by gpodevijn**

### CODE REVIEW

**Review by ClaudioDAmicoPrima — APPROVED** [review]
LGTM

**Review by danielevergara — APPROVED** [review]
LGTM

**Review by luisvicenteatprima — APPROVED** [review]
LGTM. Are there any tests we need to extend?

**Comment by gpodevijn** [comment]
> 

I added some tests and I don't think there's more to do based on the current test set.

**Review by albanovito — APPROVED** [review]
LGTM

**Pull request merged**
